# Generated by Django 2.2.3 on 2019-07-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('author', models.TextField(default='unknown')),
                ('content', models.TextField()),
                ('time_created', models.DateTimeField()),
                ('price', models.IntegerField(choices=[(0, 500), (1, 1000), (2, 1500), (3, 2000), (4, 2500), (5, 3000), (6, 3500), (7, 4000), (8, 4500), (9, 5000)])),
            ],
        ),
    ]
