# Generated by Django 2.2.3 on 2019-08-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('economy', '경제학'), ('programming', '프로그래밍'), ('math', '수학'), ('management', '경영학'), ('cpa', 'CPA/고시'), ('etc', '기타')], default='economy', max_length=15),
        ),
    ]
