# Generated by Django 2.2.3 on 2019-08-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='price',
            field=models.IntegerField(choices=[(500, 500), (1000, 1000), (1500, 1500), (2000, 2000), (2500, 2500), (3000, 3000), (3500, 3500), (4000, 4000), (4500, 4500), (5000, 5000)]),
        ),
    ]
