# Generated by Django 2.2.3 on 2019-08-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_question_tags2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags2',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
